In [1]:
#import libraries
import pandas as pd
import numpy as np
import os
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
#change directory
os.chdir("C:\\Users\\92sup\\Downloads\\PYTHON") 
#read data
fm=pd.read_csv("lastfm.csv")

In [3]:
#sample the data
fm=fm.head(500)  #limit the data set

In [4]:
#form the transactions as per user
records=fm.groupby(['user'])['artist'].apply(list).values.tolist()
#print the transactional data
records

[['red hot chili peppers',
  'the black dahlia murder',
  'goldfrapp',
  'dropkick murphys',
  'le tigre',
  'schandmaul',
  'edguy',
  'jack johnson',
  'eluveitie',
  'the killers',
  'judas priest',
  'rob zombie',
  'john mayer',
  'the who',
  'guano apes',
  'the rolling stones'],
 ['devendra banhart',
  'boards of canada',
  'cocorosie',
  'aphex twin',
  'animal collective',
  'atmosphere',
  'joanna newsom',
  'air',
  'portishead',
  'massive attack',
  'broken social scene',
  'arcade fire',
  'plaid',
  'prefuse 73',
  'm83',
  'the flashbulb',
  'pavement',
  'goldfrapp',
  'amon tobin',
  'sage francis',
  'four tet',
  'max richter',
  'autechre',
  'radiohead',
  'neutral milk hotel',
  'beastie boys',
  'aesop rock',
  'mf doom',
  'the books'],
 ['tv on the radio',
  'tool',
  'kyuss',
  'dj shadow',
  'air',
  'a tribe called quest',
  'the cinematic orchestra',
  'beck',
  'bon iver',
  'röyksopp',
  'bonobo',
  'the decemberists',
  'snow patrol',
  'battles',
  'the prodigy',
  'pink floyd',
  'rjd2',
  'the flaming lips',
  'michael jackson',
  'mgmt',
  'the rolling stones',
  'late of the pier',
  'flight of the conchords',
  'simian mobile disco',
  'muse',
  'fleetwood mac',
  'led zeppelin'],
 ['dream theater',
  'ac/dc',
  'metallica',
  'iron maiden',
  'bob marley & the wailers',
  'megadeth',
  'children of bodom',
  'trivium',
  'nightwish',
  'sublime',
  'volbeat'],
 ['lily allen',
  'kanye west',
  'sigur rós',
  'pink floyd',
  'stevie wonder',
  'metallica',
  'thievery corporation',
  'iron maiden',
  'the streets',
  'muse',
  'faith no more',
  'manu chao',
  'tenacious d',
  'depeche mode',
  'justin timberlake',
  'green day',
  'snow patrol',
  'dream theater',
  'u2',
  'jay-z',
  'type o negative',
  'pearl jam',
  'queen'],
 ['soundgarden',
  'stone temple pilots',
  'buckethead',
  'dream theater',
  'alice in chains',
  'type o negative',
  'pink floyd',
  'rush',
  'king crimson',
  'camel',
  'ac/dc',
  'tool',
  'disturbed',
  'oasis',
  'jethro tull',
  'porcupine tree',
  'audioslave',
  'aerosmith',
  'pearl jam',
  'the verve',
  'rammstein',
  'led zeppelin'],
 ['arch enemy',
  'strapping young lad',
  'kreator',
  'children of bodom',
  'iron maiden',
  'sabaton',
  'helloween',
  'mastodon',
  'pantera',
  'manowar',
  'gojira',
  'devildriver',
  'slayer',
  'hammerfall',
  'hatebreed',
  'in flames',
  'meshuggah',
  'finntroll',
  'gamma ray'],
 ['queen',
  'the beatles',
  'lynyrd skynyrd',
  'neil young',
  'the rolling stones',
  'the who',
  'led zeppelin',
  'pink floyd',
  'black sabbath',
  'the police',
  't. rex',
  'simon & garfunkel',
  'eagles',
  'jimi hendrix',
  'jethro tull',
  'bee gees',
  'van halen',
  'iron maiden',
  'bob dylan',
  'kiss',
  'ac/dc',
  'tenacious d',
  'aerosmith',
  'ennio morricone',
  'scorpions',
  'bruce springsteen',
  'dire straits',
  'guns n roses',
  'inxs',
  'rammstein'],
 ['thom yorke',
  'tom waits',
  'the notwist',
  'einstürzende neubauten',
  'the flaming lips',
  'billie holiday',
  'the books'],
 ['sonic youth',
  'the fall',
  'mogwai',
  'the velvet underground',
  'stereolab',
  'my bloody valentine',
  'the radio dept.',
  'the kinks'],
 ['sonata arctica',
  'infected mushroom',
  'iron maiden',
  'creedence clearwater revival',
  'nightwish',
  'mindless self indulgence',
  'electric light orchestra',
  'john williams',
  'michael jackson',
  'fleetwood mac',
  'aphex twin'],
 ['the kills',
  'a perfect circle',
  'crystal castles',
  'beck',
  'coldplay',
  'kent',
  'interpol',
  'nine inch nails',
  'sonic youth',
  'beirut',
  'gorillaz',
  'mgmt',
  'the radio dept.',
  'håkan hellström',
  'the kooks',
  'klaxons',
  'fischerspooner',
  'bob marley & the wailers',
  'portishead',
  'sex pistols',
  'iron & wine',
  'the shins',
  'yo la tengo',
  'the libertines',
  'thom yorke',
  'röyksopp',
  'animal collective',
  'nouvelle vague',
  'josé gonzález',
  'bloc party',
  'ladytron',
  'placebo',
  'le tigre',
  'n*e*r*d',
  'cut copy',
  'daft punk',
  'cocorosie',
  'the wombats',
  'múm',
  'the postal service',
  'franz ferdinand'],
 ['of montreal',
  'the magnetic fields',
  'devo',
  'talking heads',
  'fall out boy',
  'pinback',
  'cocorosie',
  'regina spektor',
  'interpol',
  'beck',
  'the dandy warhols',
  'the mountain goats',
  'radiohead',
  'ratatat',
  'clap your hands say yeah',
  'the strokes',
  'pixies',
  'frank zappa',
  'david bowie',
  'architecture in helsinki',
  'the sounds',
  'the beatles',
  'tom waits',
  'john frusciante',
  'mgmt',
  'beirut',
  'blink-182',
  'joy division'],
 ['the jam',
  'maxïmo park',
  'supergrass',
  'simon & garfunkel',
  'paul simon',
  'blur',
  'oasis',
  'snow patrol',
  'the who',
  'r.e.m.',
  'arctic monkeys',
  'babyshambles',
  'kasabian',
  'the libertines',
  'kings of leon',
  'pulp',
  'radiohead',
  'john lennon',
  'the strokes',
  'the stone roses',
  'dirty pretty things',
  'editors',
  'paul mccartney',
  'the cure',
  'joy division',
  'the fratellis',
  'u2',
  'david bowie',
  'doves',
  'the rolling stones',
  'the prodigy',
  'new order'],
 ['ramones',
  'the clash',
  'franz ferdinand',
  'jamiroquai',
  'the rolling stones',
  'the who',
  'radiohead',
  'the kinks',
  'mando diao',
  'the chemical brothers',
  'buzzcocks',
  'the pogues'],
 ['the byrds',
  'leonard cohen',
  'the beatles',
  'simon & garfunkel',
  'queen',
  'tom waits',
  'the beach boys',
  'neil young',
  'johnny cash',
  'the kinks',
  'bruce springsteen',
  'the rolling stones',
  'john lennon',
  'billy joel',
  'jonas brothers'],
 ['fleetwood mac',
  'madonna',
  'ladytron',
  'hooverphonic',
  'mariah carey',
  'michael jackson',
  'garbage',
  'simple plan'],
 ['toto',
  'the doors',
  'kent',
  'the smiths',
  'pink floyd',
  'sex pistols',
  'dropkick murphys',
  'bob dylan',
  'pearl jam',
  'no doubt',
  'morrissey',
  'rage against the machine',
  'various artists',
  'mötley crüe',
  'cypress hill',
  'the pogues',
  'miles davis',
  'the hives',
  'the police',
  'tool',
  'blondie',
  'jay-z',
  'jimi hendrix',
  'moby',
  'dire straits',
  'guns n roses'],
 ['stereolab',
  'hot chip',
  'tortoise',
  'r.e.m.',
  'david bowie',
  'new order',
  'hercules and love affair',
  'kate bush',
  'neil young',
  'of montreal',
  'animal collective',
  'portishead',
  'stevie wonder',
  'prince',
  'steely dan',
  'pet shop boys',
  'talking heads',
  'the cure',
  'depeche mode',
  'miles davis'],
 ['jamiroquai',
  'tori amos',
  'jazzanova',
  'radiohead',
  'st. germain',
  'marvin gaye',
  'moloko',
  'nightmares on wax',
  'the verve',
  'nick cave and the bad seeds',
  'de-phazz',
  'blonde redhead',
  'diana krall',
  'massive attack',
  'cocorosie',
  'dave matthews band',
  'the smiths',
  'jamie cullum',
  'joy division',
  'porcupine tree',
  'thievery corporation',
  'róisín murphy'],
 ['nick cave and the bad seeds',
  'black flag',
  'the gossip',
  'Édith piaf',
  'misfits',
  'deerhoof',
  'tom waits',
  'peaches',
  'turbonegro',
  'leonard cohen',
  'antony and the johnsons',
  'crystal castles',
  'the black keys',
  'minor threat',
  'of montreal',
  'devendra banhart',
  'the zombies',
  'rufus wainwright',
  'the doors',
  'the dresden dolls',
  'gogol bordello',
  'the kills',
  'nouvelle vague'],
 ['death cab for cutie',
  'tegan and sara',
  'kimya dawson',
  'die Ärzte',
  'jack johnson',
  'coldplay',
  'the kooks',
  'the fray',
  'mando diao',
  'farin urlaub',
  'a fine frenzy',
  'die toten hosen',
  'deichkind',
  'razorlight',
  'clueso',
  'evanescence',
  'linkin park',
  'seeed',
  'three days grace',
  'cute is what we aim for',
  'incubus',
  'buena vista social club',
  'counting crows',
  'paolo nutini',
  'the strokes',
  'keane',
  'belle and sebastian',
  'adam green',
  'story of the year',
  'paramore',
  'nouvelle vague',
  'ok go',
  'foo fighters'],
 ['the beatles',
  'u2',
  'the decemberists',
  'keane',
  'blind guardian',
  'vangelis',
  'moby',
  'enya',
  'johann sebastian bach',
  'kt tunstall',
  'led zeppelin',
  'blackfield',
  'lifehouse',
  'elvis presley',
  'archive',
  'enigma',
  'nightwish',
  'amy macdonald',
  'robbie williams',
  'queen',
  'belle and sebastian',
  'loreena mckennitt',
  'the doors',
  'damien rice',
  'louis armstrong',
  'a perfect circle',
  'manu chao'],
 ['radiohead',
  'the kooks',
  'coldplay',
  'nine inch nails',
  'hot chip',
  'black rebel motorcycle club',
  'lcd soundsystem',
  'kasabian',
  'n*e*r*d',
  'editors']]

In [12]:
#keep the requisite columns only
fm = fm[['user','artist']]
fm

     user                       artist
0       1        red hot chili peppers
1       1      the black dahlia murder
2       1                    goldfrapp
3       1             dropkick murphys
4       1                     le tigre
..    ...                          ...
495    35  black rebel motorcycle club
496    35              lcd soundsystem
497    35                     kasabian
498    35                      n*e*r*d
499    35                      editors

[500 rows x 2 columns]

In [13]:
#find number of unique artists and users
artists = set(fm.artist)  
users = set(fm.user) 
print(len(artists),len(users))

346 24

In [14]:
#create a dataframe with unique artists as column names
df = pd.DataFrame(columns = artists)
df

Empty DataFrame
Columns: [jonas brothers, counting crows, mastodon, john mayer, toto, kyuss, loreena mckennitt, moby, t. rex, incubus, black rebel motorcycle club, hammerfall, the cure, jamiroquai, amon tobin, sigur rós, nightmares on wax, the streets, john williams, mf doom, minor threat, bloc party, a tribe called quest, tori amos, cut copy, prince, david bowie, kreator, a fine frenzy, helloween, my bloody valentine, creedence clearwater revival, new order, blink-182, clueso, bonobo, the kills, supergrass, vangelis, judas priest, the black keys, the clash, the books, mando diao, kasabian, u2, lily allen, the flaming lips, the velvet underground, blackfield, robbie williams, infected mushroom, miles davis, steely dan, einstürzende neubauten, massive attack, mötley crüe, simian mobile disco, beck, the kooks, röyksopp, the doors, foo fighters, john frusciante, kimya dawson, blonde redhead, amy macdonald, dave matthews band, thom yorke, john lennon, radiohead, buckethead, the beach boys, ramones, justin timberlake, yo la tengo, blind guardian, manowar, kanye west, keane, children of bodom, black sabbath, paramore, pulp, ratatat, róisín murphy, schandmaul, johnny cash, jimi hendrix, arch enemy, aerosmith, doves, led zeppelin, the wombats, gogol bordello, a perfect circle, interpol, guns n roses, johann sebastian bach, bee gees, ...]
Index: []

[0 rows x 346 columns]

In [15]:
#loop to fill the values in dataframe in binary format
for user in set(fm.user):
    for i in records:
        temp={}
        for  element in i:
            temp[element]=1
        df = df.append(temp, ignore_index = True)
df

,jonas brothers,counting crows,mastodon,john mayer,toto,kyuss,loreena mckennitt,moby,t. rex,incubus,...,klaxons,goldfrapp,placebo,strapping young lad,blondie,the beatles,the prodigy,the police,stone temple pilots,black flag
0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
573,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
574,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#set the null values as 0
df[df.isnull()] = 0 
df

,jonas brothers,counting crows,mastodon,john mayer,toto,kyuss,loreena mckennitt,moby,t. rex,incubus,...,klaxons,goldfrapp,placebo,strapping young lad,blondie,the beatles,the prodigy,the police,stone temple pilots,black flag
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
572,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
573,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
574,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
#apply the apriory rule with min support hence to create the frequently used transaction pair
freq_itemset = apriori(df=df, min_support = 0.1, use_colnames = True) # Finding the support for the artists
freq_itemset

     support                                 itemsets
0   0.125000                            (david bowie)
1   0.125000                                     (u2)
2   0.125000                                   (beck)
3   0.125000                              (the kooks)
4   0.125000                              (the doors)
5   0.250000                              (radiohead)
6   0.166667                           (led zeppelin)
7   0.125000                             (portishead)
8   0.166667                                (the who)
9   0.125000                                   (tool)
10  0.208333                             (pink floyd)
11  0.125000                          (dream theater)
12  0.125000                         (nouvelle vague)
13  0.125000                              (the kinks)
14  0.166667                                  (queen)
15  0.125000                              (pearl jam)
16  0.250000                     (the rolling stones)
17  0.125000                                  (ac/dc)
18  0.125000                               (coldplay)
19  0.125000                      (animal collective)
20  0.208333                            (iron maiden)
21  0.125000                          (fleetwood mac)
22  0.166667                              (tom waits)
23  0.166667                              (cocorosie)
24  0.125000                                   (mgmt)
25  0.125000                        (michael jackson)
26  0.125000                            (of montreal)
27  0.125000                            (the strokes)
28  0.125000                              (nightwish)
29  0.125000                      (simon & garfunkel)
30  0.125000                            (snow patrol)
31  0.125000                             (neil young)
32  0.125000                           (joy division)
33  0.166667                            (the beatles)
34  0.125000                             (beck, mgmt)
35  0.125000                    (coldplay, the kooks)
36  0.125000                   (cocorosie, radiohead)
37  0.125000                (radiohead, joy division)
38  0.125000               (led zeppelin, pink floyd)
39  0.125000          (animal collective, portishead)
40  0.166667            (the who, the rolling stones)
41  0.125000                       (pink floyd, tool)
42  0.125000                  (pearl jam, pink floyd)
43  0.125000                     (the beatles, queen)
44  0.125000  (simon & garfunkel, the rolling stones)
45  0.125000         (fleetwood mac, michael jackson)

In [18]:
#apply association rule
rules = association_rules(freq_itemset, min_threshold = 0.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(beck),(mgmt),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
1,(mgmt),(beck),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
2,(coldplay),(the kooks),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
3,(the kooks),(coldplay),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
4,(cocorosie),(radiohead),0.166667,0.250000,0.125000,0.750000,3.0,0.083333,3.000000
5,(radiohead),(cocorosie),0.250000,0.166667,0.125000,0.500000,3.0,0.083333,1.666667
6,(radiohead),(joy division),0.250000,0.125000,0.125000,0.500000,4.0,0.093750,1.750000
7,(joy division),(radiohead),0.125000,0.250000,0.125000,1.000000,4.0,0.093750,inf
8,(led zeppelin),(pink floyd),0.166667,0.208333,0.125000,0.750000,3.6,0.090278,3.166667
9,(pink floyd),(led zeppelin),0.208333,0.166667,0.125000,0.600000,3.6,0.090278,2.083333
10,(animal collective),(portishead),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
11,(portishead),(animal collective),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
12,(the who),(the rolling stones),0.166667,0.250000,0.166667,1.000000,4.0,0.125000,inf
13,(the rolling stones),(the who),0.250000,0.166667,0.166667,0.666667,4.0,0.125000,2.500000
14,(pink floyd),(tool),0.208333,0.125000,0.125000,0.600000,4.8,0.098958,2.187500
15,(tool),(pink floyd),0.125000,0.208333,0.125000,1.000000,4.8,0.098958,inf
16,(pearl jam),(pink floyd),0.125000,0.208333,0.125000,1.000000,4.8,0.098958,inf
17,(pink floyd),(pearl jam),0.208333,0.125000,0.125000,0.600000,4.8,0.098958,2.187500
18,(the beatles),(queen),0.166667,0.166667,0.125000,0.750000,4.5,0.097222,3.333333
19,(queen),(the beatles),0.166667,0.166667,0.125000,0.750000,4.5,0.097222,3.333333
20,(simon & garfunkel),(the rolling stones),0.125000,0.250000,0.125000,1.000000,4.0,0.093750,inf
21,(the rolling stones),(simon & garfunkel),0.250000,0.125000,0.125000,0.500000,4.0,0.093750,1.750000
22,(fleetwood mac),(michael jackson),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf
23,(michael jackson),(fleetwood mac),0.125000,0.125000,0.125000,1.000000,8.0,0.109375,inf